preload = /home/nobel/.config/aether/theme/backgrounds/wallhaven-1p5z71.jpg

wallpaper {
    monitor = eDP-1
    path = /home/nobel/.config/aether/theme/backgrounds/wallhaven-1p5z71.jpg
    fit_mode = cover
}

splash = false
