# =====================================================================
# HYPRPAPER - Wallpaper
# =====================================================================
# Ajusta la ruta a tu wallpaper real antes de aplicar
preload = ~/dotfiles/hypr/.config/hypr/wallpaper.jpg
wallpaper = ,~/dotfiles/hypr/.config/hypr/wallpaper.jpg
splash = false
