# ==========================================
# HYPRIDLE - Gestión de inactividad
# ==========================================

general {
    # Evita instancias duplicadas si el WM se reinicia
    lock_cmd = pidof hyprlock || hyprlock
    # Bloquea ANTES de suspender (tapa cerrada, suspend manual)
    before_sleep_cmd = loginctl lock-session
    # Al despertar, reactiva los paneles inmediatamente
    after_sleep_cmd = hyprctl dispatch dpms on
}

# A los 3 min de inactividad: bloquear sesión
listener {
    timeout = 180
    on-timeout = loginctl lock-session
}

# A los 8 min: apagar paneles (DPMS). Al mover el mouse, encienden
listener {
    timeout = 480
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
