# =====================================================================
# HYPRSUNSET - Temperatura de color automática
# =====================================================================

# Perfil nocturno: cálido, se activa según hora del sistema
profile {
    time = 19:00
    temperature = 3500
}

profile {
    time = 07:00
    temperature = 6500
}
