preload = /home/nobel/.config/aether/theme/backgrounds/wallhaven-216kmm.png

wallpaper {
    monitor = eDP-1
    path = /home/nobel/.config/aether/theme/backgrounds/wallhaven-216kmm.png
    fit_mode = cover
}

splash = false
